debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Ifcc8f41063e36722c5c2a0a5d0bf64ebe2b1f910

Former-commit-id: 67cb72b0039001522b6c880d483811e7716fe6e8